/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_xh_xEye_jni_EquipJNI */

#ifndef _Included_com_xh_xEye_jni_EquipJNI
#define _Included_com_xh_xEye_jni_EquipJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xh_xEye_jni_EquipJNI
 * Method:    loginEquip
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/xh/xEye/domain/LoginDvrVO;
 */
JNIEXPORT jobject JNICALL Java_com_xh_xEye_jni_EquipJNI_loginEquip
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     com_xh_xEye_jni_EquipJNI
 * Method:    getDeviceList
 * Signature: (IIII)Lcom/xh/xEye/domain/ArrayOfCI;
 */
JNIEXPORT jobject JNICALL Java_com_xh_xEye_jni_EquipJNI_getDeviceList
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_xh_xEye_jni_EquipJNI
 * Method:    getDevGroupsByCode
 * Signature: (ILjava/lang/String;I)Lcom/xh/xEye/domain/ArrayOfThirdGroup;
 */
JNIEXPORT jobject JNICALL Java_com_xh_xEye_jni_EquipJNI_getDevGroupsByCode
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_xh_xEye_jni_EquipJNI
 * Method:    getDevicesByCode
 * Signature: (ILjava/lang/String;II)Lcom/xh/xEye/domain/ArrayOfCI;
 */
JNIEXPORT jobject JNICALL Java_com_xh_xEye_jni_EquipJNI_getDevicesByCode
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     com_xh_xEye_jni_EquipJNI
 * Method:    logoutEquip
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xh_xEye_jni_EquipJNI_logoutEquip
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xh_xEye_jni_EquipJNI
 * Method:    getDomain
 * Signature: (I)Lcom/xh/xEye/domain/DomainVO;
 */
JNIEXPORT jobject JNICALL Java_com_xh_xEye_jni_EquipJNI_getDomain
  (JNIEnv *, jclass, jint);

/*
* Class:     com_xh_xEye_jni_EquipJNI
* Method:    getDomainEx
* Signature: (I)Lcom/xh/xEye/domain/ArrayOfDomain;
*/
JNIEXPORT jobject JNICALL Java_com_xh_xEye_jni_EquipJNI_getDomainEx
(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
